// ==================== IMPORT MONGOOSE ====================

// Import Mongoose to create the Product schema and model
const mongoose = require("mongoose");


// ==================== PRODUCT SCHEMA ====================

// Define the structure of a Product document in MongoDB
const productSchema = new mongoose.Schema(
    {
        // ==================== VENDOR RELATIONSHIP ====================

        // Stores the MongoDB ID of the vendor who owns this product
        vendor: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Vendor",
            required: true
        },


        // ==================== BASIC PRODUCT INFORMATION ====================

        // Name of the product
        name: {
            type: String,
            required: true,
            trim: true
        },

        // Description of the product
        description: {
            type: String,
            required: true,
            trim: true
        },

        // Category of the product
        category: {
            type: String,
            required: true,
            trim: true
        },

        // Selling price of the product
        price: {
            type: Number,
            required: true,
            min: 0
        },

        // Number of product units currently available
        stock: {
            type: Number,
            required: true,
            min: 0,
            default: 0
        },

        // URL of the uploaded product image
        imageUrl: {
            type: String,
            default: ""
        },

        // ==================== COMPARABLE PRODUCT IDENTIFIER ====================
        // Optional minimal model identifier (e.g., 'iPhone 15', 'Gaming Mouse')
        // Used to group comparable offers from different vendors.
        // Fallback is normalized product name if not explicitly set.
        productModel: {
            type: String,
            trim: true,
            default: ""
        },


        // ==================== ADVANCED - AI GENERATED TAGS ====================

        // Tags generated by the AI/Vision model
        aiTags: {
            type: [String],
            default: []
        },


        // ==================== ADVANCED - SEO KEYWORDS ====================

        // SEO keywords generated by the GenAI model
        seoKeywords: {
            type: [String],
            default: []
        },


        // ==================== ADVANCED - VECTOR EMBEDDING ====================

        // 768-dimensional vector embedding for semantic search
        embedding: {
            type: [Number],
            default: []
        }
    },

    // Automatically add createdAt and updatedAt
    {
        timestamps: true
    }
);


// ==================== PRODUCT MODEL ====================

// Create the Product model using productSchema
const Product = mongoose.model("Product", productSchema);


// ==================== EXPORT MODEL ====================

// Export Product so controllers and other files can use it
module.exports = Product;